version: '3'

volumes:
  localstack-data:
    driver: local

services:
  localstack:
    image: localstack/localstack:0.11.0
    container_name: localstack-for-kcl
    ports:
      - "8080:8080"
      - "4566:4566"
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=${LOCALSTACK_DEBUG:-true}
      - DEFAULT_REGION=ap-northeast-1
      - SERVICES=dynamodb,kinesis
      - USE_SSL=true
    volumes:
      - "${PWD}/aws:/root/.aws"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack-data:/tmp/localstack"
